flaskblog/posts/forms.py
# coding: utf-8
# @Author   : wangkui
# @Time     : 2020/07/15 13:32
# @File     : forms
# @Platform : VSCode
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length

class CreatePostForm(FlaskForm):
	"""docstring for CreatePostForm"""
	title = StringField('Title', validators=[DataRequired(), Length(min=1, max=50)])
	content = TextAreaField('Content', validators=[DataRequired()])
	submit = SubmitField('Submit')

flaskblog/main/routes.py
# coding: utf-8
# @Author   : wangkui
# @Time     : 2020/07/15 13:08
# @File     : routes
# @Platform : VSCode

from flask import Blueprint, request, render_template
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route('/')
def index():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
	return render_template('home.html', posts=posts)

@main.route('/about')
def about():
	return render_template('about.html', title='About')

flaskblog/posts/__init__.py
# coding: utf-8
# @Author   : wangkui
# @Time     : 2020/07/15 13:06
# @File     : __init__
# @Platform : VSCode

flaskblog/posts/routes.py
# coding: utf-8
# @Author   : wangkui
# @Time     : 2020/07/15 13:08
# @File     : routes
# @Platform : VSCode
from datetime import datetime
from flaskblog.posts.forms import CreatePostForm
from flaskblog import db
from flask import Blueprint, flash, redirect, render_template, url_for, abort, request
from flask_login import login_required, current_user
from flaskblog.models import Post

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def create_post():
	form = CreatePostForm()
	if form.validate_on_submit():
		title = form.title.data
		content = form.content.data
		author = current_user
		post = Post(title=title, date_posted=datetime.today().ctime(), content=content, author=author)
		try:
			db.session.add(post)
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			flash(f'create post error {e}', 'danger')
		else:
			flash(f'Post {form.title.data} has been created!', 'success')
			return redirect(url_for('main.index'))
	return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = CreatePostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		try:
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			flash(f'update post error {e}', 'danger')
		else:
			flash(f'update post success', 'success')
		finally:
			return redirect(url_for('posts.post', post_id=post.id))

	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title=post.title, form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)

	try:
		db.session.delete(post)
		db.session.commit()
	except Exception as e:
		db.session.rollback()
		flash(f'delete post error {e}', 'danger')
	else:
		flash(f'delete post success', 'success')
	finally:
		return redirect(url_for('main.index'))

flaskblog/users/routes.py
# coding: utf-8
# @Author   : wangkui
# @Time     : 2020/07/15 13:07
# @File     : routes
# @Platform : VSCode
from flaskblog.users.utils import reset_email, save_img
from flaskblog.users.forms import LoginForm, RegistrationForm, ResetPasswordForm, ResetRequestEmailForm, UpdateAccountForm
from flask import Blueprint, redirect, url_for, flash, render_template, request, abort
from flask_login import current_user, login_user, logout_user, login_required
from flaskblog.models import User, Post
from flaskblog import bcrypt, db

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = RegistrationForm()
	if form.validate_on_submit():
		username = form.username.data
		email = form.email.data
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=username, email=email, password=hashed_password)
		try:
			db.session.add(user)
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			flash(f'db commit error {e}', 'danger')
			return redirect(url_for('main.index'))
		else:
			flash(f'Account {form.username.data} has been created!', 'success')
			return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			flash(f'{form.email.data} have been logged in!', 'success')
			return redirect(next_page) if next_page else redirect(url_for('main.index'))
		else:
			flash('Login Unsuccessful. Please check email and password!', 'danger')
	return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.index'))

@users.route('/account/<string:user_name>', methods=['GET', 'POST'])
@login_required
def account(user_name):
	if user_name != current_user.username:
		abort(403)
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.image.data:
			image_file = save_img(form.image.data)
			if image_file == None:
				flash('Upload image failed. Please try again!', 'danger')
				return redirect(url_for('users.account', user_name=current_user.username))
			current_user.image_file = image_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		try:
			db.session.commit()
		except Exception as e:
			db.session.rollback()
			flash(f'update account error {e}', 'danger')
		else:
			flash(f'update account success', 'success')
		finally:
			return redirect(url_for('users.account', user_name=current_user.username))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('account.html', title=current_user.username, image_file=image_file, form=form)

@users.route('/posts/<string:user_name>', methods=['GET', 'POST'])
def user_posts(user_name):
	user = User.query.filter_by(username=user_name).first_or_404()
	page = request.args.get('page', 1, type=int)
	posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
	# posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
	return render_template('user_posts.html', posts=posts, user=user)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	form = ResetRequestEmailForm()
	if form.validate_on_submit():
		# send reset email
		user = User.query.filter_by(email=form.email.data).first()
		reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.index'))
	user = User.verify_user_token(token)
	if user == None:
		flash('Request link has been experied or invalid.', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		# change password
		password = form.password.data
		hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
		user.password = hashed_password
		try:
			db.session.commit()
		except:
			flash('Reset password error!', 'danger')
		else:
			flash('Reset password success!', 'success')
			return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}

{% block content %}
<h1>About Pages</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src={{ image_file }}>
	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email }}</p>
	    </div>
	  </div>
	  <!-- FORM HERE -->
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Update Account
				</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
					{{ form.username(class="form-control form-control-lg") }}
					<div class="invalid-feedback d-block">
						{% for error in form.username.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg") }}
					<div class="invalid-feedback d-block">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.image.label() }}
					{{ form.image(class="form-control-file") }}
					{% if form.image.errors %}
					<div class="invalid-feedback d-block">
						{% for error in form.image.errors %}
						<span>{{ error }}</span></br>
						{% endfor %}
					</div>
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>
	</div>
<p>this is <b>{{ current_user.username }}'s</b> main page.</p>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">
				{{ legend }}
			</legend>
			<div class="form-group">
				{{ form.title.label(class="form-control-label") }}
				{% if form.title.errors %}
				{{ form.title(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.title.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.title(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.content.label(class="form-control-label") }}
				{% if form.content.errors %}
				{{ form.content(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.content.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.content(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>

{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}
{% for post in posts.items %}
<!-- custom home page post's CSS -->
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', user_name=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2 class="article-title"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for post_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if post_num %}
    {% if posts.page == post_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('main.index', page=post_num) }}"><strong>{{ post_num }}</strong></a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('main.index', page=post_num) }}">{{ post_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
	<title>Flask Blog - {{ title }}</title>
	{% else %}
	<title>Flask Blog</title>
	{% endif %}
</head>
<body>
	<!-- navigation -->
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Flask Blog</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
	          <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %}
	          <a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">New Post</a>
	          <a class="nav-item nav-link" href="{{ url_for('users.account', user_name=current_user.username) }}">{{ current_user.username }}</a>
	          <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

	        	{% else %}
	          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
	          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
	          {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<!-- main content -->
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    {% with messages = get_flashed_messages(with_categories=true) %}
	    {% if messages %}
	    {% for category, message in messages %}
	    <div class="alert alert-{{ category }}">
	    	{{ message }}
	    </div>
	    {% endfor %}
	    {% endif %}
	    {% endwith %}
	      {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</main>
	<!-- Bootstrap JS -->
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">
				Sign In
			</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-check">
				{{ form.remember(class="form-check-input") }}
				{{ form.remember.label(class="form-check-label") }}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
			<small class="text-muted ml-2">
				<a href="{{ url_for('users.reset_request') }}">Forget Password</a>
			</small>
		</div>
	</form>
</div>
<div class="border-top pt-3">
	<small class="text-muted">
		Don't Have An Account? Please<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
	</small>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}

{% block content %}
<!-- custom home page post's CSS -->
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.account', user_name=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
      <div>
      	<a class="btn btn-outline-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
      	<button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        you sure?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
        	<input type="submit" class="btn btn-danger" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">
				Join Today
			</legend>
			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{% if form.username.errors %}
				{{ form.username(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.username.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.username(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }}
				{% if form.confirm_password.errors %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.confirm_password.errors %}
						<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
					{{ form.confirm_password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
<div class="border-top pt-3">
	<small class="text-muted">
		Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
	</small>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">
				Reset Password
			</legend>
			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">
				Reset Password
			</legend>
			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-group">
				{{ form.confirm_password.label(class="form-control-label") }}
				{% if form.confirm_password.errors %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
				<div class="invalid-feedback d-block">
					{% for error in form.confirm_password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>
	</form>
</div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
<h1 class="mb-3">Posts by {{ user.username }} (total: {{ posts.total }})</h1>
{% for post in posts.items %}
<!-- custom home page post's CSS -->
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.user_posts', user_name=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2 class="article-title"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for post_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if post_num %}
    {% if posts.page == post_num %}
      <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', user_name=user.username, page=post_num) }}"><strong>{{ post_num }}</strong></a>
    {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', user_name=user.username, page=post_num) }}">{{ post_num }}</a>
    {% endif %}
  {% else %}
    ...
  {% endif %}
{% endfor %}
{% endblock content %}